apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0.2
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_DATABASE
            value: mongodb
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: mongouser
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: mongopwd